CREATE TABLE IF NOT EXISTS accounts (
    id TEXT PRIMARY KEY,
    balance DECIMAL NOT NULL DEFAULT 0.00
);
INSERT INTO accounts (id, balance) VALUES ('ZA001', 100000000000.00) ON CONFLICT (id) DO NOTHING;

CREATE TABLE IF NOT EXISTS colbee_core_status (
    id SERIAL PRIMARY KEY,
    status TEXT NOT NULL,
    launched_at TIMESTAMPTZ DEFAULT NOW()
);
INSERT INTO colbee_core_status (status) VALUES ('COLBEE RUST CORE v4.2.0 — SARB NODE ACTIVE') ON CONFLICT DO NOTHING;
